name: build_and_deploy
on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: npm install
    - run: npm run build
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: build/
        remote_path: /opt/applications/books-fe/
        remote_host: 3.237.77.85
        remote_user: ubuntu
        remote_key: ${{ secrets.DEPLOY_KEY }}
